FROM docker.io/node:21.6.2
WORKDIR /app
COPY package*.json ./
RUN npm install -g pnpm
RUN pnpm install
COPY . .
# RUN apt-get update && 
RUN npm run prisma:generate

RUN npm run build

# COPY .next ./
CMD ["npm", "run", "dev"]
